---
driver:
  name: dokken
  chef_version: <%= ENV['KITCHEN_CHEF_VER'] || 12 %>

transport:
  name: dokken

provisioner:
  name: dokken

platforms:
  - name: ubuntu-16.04
    driver:
      image: dokken/ubuntu-16.04
      pid_one_command: /bin/systemd
      privileged: true
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup
      intermediate_instructions:
        - RUN /usr/bin/apt-get update
  - name: ubuntu-14.04
    driver:
      image: dokken/ubuntu-14.04
      pid_one_command: /sbin/init
  - name: centos-6
    driver:
      image: dokken/centos-6
      pid_one_command: /sbin/init
  - name: centos-7
    driver:
      image: dokken/centos-7
      privileged: true
      pid_one_command: /usr/lib/systemd/systemd
  - name: freebsd-11
    driver:
      name: vagrant
      provider: parallels
    provisioner:
      name: chef_zero
    transport:
      name: ssh

verifier:
  name: inspec
  reporter: junit
  inspec_tests:
    - path: test/smoke/default

suites:
  - name: default-beats
    run_list:
      - recipe[beats_test]
