---
driver:
  name: vagrant
  provider: parallels
  server_name_prefix: "chef_beats"
provisioner:
  name: chef_zero
  product_version: <%= ENV['KITCHEN_CHEF_VER'] || 14 %>
  always_update_cookbooks: true
platforms:
  - name: ubuntu-16.04
  - name: ubuntu-14.04
  # - name: freebsd-11
  # - name: centos-7
  # - name: debian-9
verifier:
  name: inspec
  reporter: junit
suites:
  - name: default-beats
    run_list:
      - recipe[beats_test]
